### ISSUE TITLE
A whitespace after if(){}else{} is not showing

### ISSUE THREAD

**Issue by yousuketto** [playframework/twirl#711] opened 2023-11-13 08:09 UTC
A whitespace after `if(condition) {...} else {...}` is not showing.

## Reproduction
scalaVersion = "2.13.12"
sbt-twirl version: `1.6.2` (Reproduced in `1.6.0-M1+38-e141ce17-SNAPSHOT`, Not reproduced in `"1.6.0-M1+35-de50d09a-SNAPSHOT`)

### code
```
$ cat src/main/twirl/com/github/yousuketto/sample.scala.txt
@(b: Boolean)
You got @if(b) {a pullrequest} else {pullrequests} from someone.
```

### Execute in sbt console
```
scala> com.github.yousuketto.txt.sample(false)
val res0: play.twirl.api.TxtFormat.Appendable =
You got pullrequestsfrom someone.

scala> com.github.yousuketto.txt.sample(true)
val res1: play.twirl.api.TxtFormat.Appendable =
You got a pullrequestfrom someone.

scala>
```

### Expected
```
scala> com.github.yousuketto.txt.sample(true)
val res0: play.twirl.api.TxtFormat.Appendable =
You got a pullrequest from someone.

scala> com.github.yousuketto.txt.sample(true)
val res1: play.twirl.api.TxtFormat.Appendable =
You got a pullrequest from someone.

scala>
```

**Comment by mkurz** [comment] 2023-11-13 08:15
According to
```
git log de50d09a..e141ce17
```

this must be caused by e8b6ceb2542f90e7c1baa18cea5fcc3688a0d3ad

@tototoshi or also @yousuketto can you take a look here and provide a pull request if you have time? Also a test would be great, thanks! I may fix that, but have lots of other stuff to do, so it might take a while.

**Comment by mkurz** [comment] 2023-11-16 10:20
Fixed by
- #712

**Closed by mkurz** 2023-11-16 10:20 UTC
